### ISSUE TITLE
How can zukeeper be added as middleware?

### ISSUE THREAD

**Issue by pinkynrg** [dhmk083/dhmk-zustand-lens#20]
when add zukeeper as middleware like so:

```
import { create } from 'zustand'
import { immer } from 'zustand/middleware/immer'
import zukeeper from 'zukeeper'
import { withLenses } from '@dhmk/zustand-lens'
import { categories } from '../slices/categories'
import { projects } from '../slices/projects'
import { ui } from '../slices/ui'
import { IStore } from './types'
import { brandStyles } from '../slices/brandStyles'
import { listItemsInstance } from '../slices/listItemsInstance'

const useApplicationStore = create<IStore>()(
  zukeeper(
    immer(
      withLenses(() => ({
        ui,
        categories,
        brandStyles,
        projects,
        listItemsInstance,
      })),
    ),
  ),
)

window.store = useApplicationStore

export { useApplicationStore }
```

I get this error:

```
main.3b53a5f….js:54795 Uncaught TypeError: Cannot set properties of undefined (setting 'setState')
    at eval (immer.mjs:9:18)
    at eval (index.js:6:19)
    at createStoreImpl (vanilla.mjs:32:32)
    at createStore (vanilla.mjs:35:52)
    at createImpl (index.mjs:43:111)
    at eval (index.ts:12:1)
    at ./src/zustandStore/store/index.ts (main.3b53a5f….js:52692:1)
    at __webpack_require__ (main.3b53a5f….js:54792:33)
    at fn (main.3b53a5f….js:55045:21)
    at eval (LoginModal.tsx:23:78)
```

**Comment by dhmk083** [comment]
I looked at zukeeper's code and there is an error on its side. Original zustand `create` function calls middleware with three arguments: `set`, `get` and `store`. But zukeeper doesn't use `store` argument, so it got lost. Here is a part of its code:

```ts
function zukeeper(createFunction) {
  return (set, get) => {
    const store = createFunction(set, get);
...
```
